export { default as home } from './home.vue'
export { default as triangle } from './triangle.vue'
export { default as exit } from './exit.vue'
export { default as leftArrow } from './leftArrow.vue'
export { default as rightArrow } from './rightArrow.vue'
